const acceptanceAddress = [[
				{id:1,label:'金华市双龙派出所'},
				{id:2,label:'金华市白龙派出所'},
				{id:3,label:'金华市东关派出所'},
				{id:4,label:'金华市站前派出所'},
				{id:5,label:'金华市江南派出所'},
				{id:6,label:'金华市城东派出所'},
				{id:7,label:'金华市城北派出所'},
				{id:8,label:'金华市车站派出所'},
				{id:9,label:'金华市新狮派出所'},
				{id:10,label:'金华市城中派出所'},
				{id:11,label:'金华市城西派出所'},
				{id:12,label:'金华市城西派出所'},
				{id:13,label:'金华市罗埠派出所'},
				{id:14,label:'金华市雅畈派出所'},
				{id:15,label:'金华市西关派出所'},
				{id:16,label:'金华市苏孟派出所'},
				{id:17,label:'金华市三江派出所'},
				{id:18,label:'金华市秋滨派出所'},
				{id:19,label:'金华市琅琊派出所'},
				{id:20,label:'金华市汤溪派出所'},
				{id:21,label:'金华市蒋堂派出所'},
				{id:22,label:'金华市付村派出所'},
				{id:23,label:'金华市鞋塘派出所'},
				{id:24,label:'金华市孝顺派出所'},
				{id:25,label:'金华市曹宅派出所'},
				{id:26,label:'金华市塘雅派出所'},
				{id:27,label:'金华市澧浦派出所'},
				{id:28,label:'金华市多湖派出所'},
				{id:29,label:'金华市赤松派出所'},
				{id:30,label:'金华市岭下派出所'},
				{id:31,label:'金华市公安局婺城分局森林派出所'},
				{id:32,label:'水上派出所'}
			]]
export default acceptanceAddress
 